export const ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjYmM2MmRiNjNkNTFiNDFmNzdiMmEwYTFkNWFlNGIyYyIsInN1YiI6IjYwOTI0MzM3NTQ1MDhkMDA2ZjFlMmU4OCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.y-dWnWlInitMZLgz92o1TKqqXbnUEuYj2K3oAx9kcDg"

export const BASE_URL = "https://api.themoviedb.org/3"